# This workflow runs every five minutes to check for a new twitch status
name: Check for new Twitch status
on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install PNPM
        uses: pnpm/action-setup@v4

      # Yarn dependencies cannot be cached until pnpm is installed
      # WORKAROUND: https://github.com/actions/setup-node/issues/531
      - name: Extract cached dependencies
        uses: actions/setup-node@v4
        with:
          cache: pnpm

      - name: Install
        run: pnpm i --frozen-lockfile --prefer-offline

      - name: Check for twitch status update
        run: pnpm start
        env:
          TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
          TWITCH_CLIENT_SECRET: ${{ secrets.TWITCH_CLIENT_SECRET }}

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          base: HEAD
          filters: |
            any:
              - '**/*'

      - name: Commit latest status
        if: ${{ steps.filter.outputs.any == 'true' }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: new twitch status"
